---
- name: Installs Rundeck
  hosts: all
  become: true
  vars:
    - rundeck_mysql_backend: false
  roles:
    - role: ansible-mariadb-mysql
      when: >
            rundeck_mysql_backend is defined and
            rundeck_mysql_backend
    - role: ansible-rundeck
  tasks:
